[general]
import = ["alacritty-theme/themes/gruvbox_dark.toml"]
live_config_reload = true

[font]
normal = { family = "0xProto Nerd Font Mono", style = "Regular" }
# normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }
size = 14 

[cursor]
style = { shape = "Beam", blinking = "Always" }

[window]
padding = { x = 14, y = 30 }
decorations = "Transparent" 
blur = true
opacity = 0.3
startup_mode = "Maximized"

[keyboard]
bindings = [
  { key = "Left",    mods = "Alt",     chars = "\u001bb" },
  { key = "Right",   mods = "Alt",     chars = "\u001bf" },
  { key = "Left",    mods = "Command", chars = "\u001bOH", mode = "AppCursor" },
  { key = "Right",   mods = "Command", chars = "\u001bOF", mode = "AppCursor" },
  { key = "Back",    mods = "Command", chars = "\u0015" },
  { key = "Back",    mods = "Alt",     chars = "\u001b\u007f" }
]
